#!/usr/bin/env bash
self_dir=$(cd "$(dirname "$(stat -f %Y "$0")")" || exit; pwd -P)

if [ -f "$self_dir/$1.sh" ]; then
    "$self_dir/$1.sh" "${@:2}"
    exit $?
else
    echo "Script not found: $1" >&2
    exit 1
fi
